baseURL: "https://hoyekan.github.io/"
title: "Hammed Oyekan"
theme: "PaperMod"
languageCode: "en-us"

# Replaced deprecated paginate with new pagination format
pagination:
  pagerSize: 20

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
  tags: "tags"

menu:
  main:
    # - identifier: "about"
    #   name: "About"
    #   url: "/about/"
    #   weight: 1

    - identifier: "research"
      name: "Research"
      url: "/research/"
      weight: 2

    - identifier: "projects"
      name: "Projects"
      url: "/projects/"
      weight: 3

    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 4

    - identifier: "design"
      name: "Design"
      url: "/design/"
      weight: 5

    - identifier: "gallery"
      name: "Gallery"
      url: "/gallery/"
      weight: 6
      
params:
  description: "Still learning. Still building."
  author: "OYEKAN, Hammed"
  DateFormat: "January 2, 2006"
  defaultTheme: "light"
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  
  coverImageMode:
    enabled: false
    imageUrl: "/in_the_name_of_Allah.jpeg"
    # imageUrl: "/images/in_the_name_of_Allah.jpeg"
    # imageUrl: "https://hoyekan.github.io/in_the_name_of_Allah.jpeg"
    # imageUrl: "https://raw.githubusercontent.com/hoyekan/hoyekan.github.io/main/static/in_the_name_of_Allah.jpeg"
    imageWidth: 170
    imageHeight: 55
    imageTitle: "In the name of Allah"
  
  # cover:
    # image: "/in_the_name_of_Allah.jpeg"
    # alt: "In the name of Allah"
    
  profileMode:
    enabled: true
    title: "OYEKAN, Hammed"
    subtitle: |
      Welcome to my website! I am an aspiring computational and exploration seismologist/geophysicist. 
      <br/><br/> I recently received my MSc in Geophysics (on the 31 of December, 2024) from King Fahd University of Petroleum and Minerals (KFUPM), Dhahran, Saudi Arabia, under the supervision of <a href="https://faculty.kfupm.edu.sa/es/ashuhail/" target="_blank" style="color:#8e7bd0">Prof. Abdullatif A. Al-Shuhail</a>. 
      <br/><br/> My area of interest are in **Wave propagation**, **theoretical seismology**, **Seismic data processing/analysis**, **imaging**, and **inversion**, **Full-waveform inversion (FWI)**, and **Numerical modelling**
      <br/><br/> I am currently open to collaborations and new opportunities.
    imageUrl: "profile.jpeg"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: Curriculum Vitae
        url: cv/
      - name: "Research"
        url: "/research/"
      - name: "Projects"
        url: "/projects/"
      - name: "Teaching"
        url: "/teaching/"
      - name: "Courses"
        url: "/courses/"
      - name: "News"
        url: "/news/"
      # - name: "Location"
      #   url: "location/"

  socialIcons:
    - name: CV
      url: cv.pdf
    - name: email
      url: mailto:oyekan.geophysics@gmail.com
    - name: googlescholar
      url: https://scholar.google.com/
    - name: researchgate
      url: https://www.researchgate.net/profile/Hammed-Oyekan/research
    - name: github
      url: https://github.com/hoyekan
    - name: linkedin
      url: https://www.linkedin.com/in/oyekan-hammed

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    # hiddenInList: true
    hiddenInSingle: true
  label:
    text: "OYEKAN, Hammed A."
    icon: "/favicon.ico"
    # icon: "/favicon-whale.ico"
    iconHeight: 18
      
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

enableEmoji: true
pygmentsUseClasses: true
pygmentsCodeFences: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    # style: "xcode"
    style: "autumn" 
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
